# Generated by Django 5.2.12 on 2026-04-02 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('product', '0002_stock_parent'),
        ('roles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseapproval',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.role'),
        ),
        migrations.AddField(
            model_name='purchasebook',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebook',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.location'),
        ),
        migrations.AddField(
            model_name='purchasebook',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.stock'),
        ),
        migrations.AddField(
            model_name='purchaseapproval',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='document.purchasebook'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseapproval',
            unique_together={('purchase', 'sequence')},
        ),
    ]
