# Generated by Django 5.1.1 on 2026-04-05 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
        ('product', '0002_stock_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasebook',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_purchase', 'Can create purchase'), ('can_view_all_purchases', 'Can view all purchases'), ('can_cancel_purchase', 'Can cancel purchase'), ('can_do_first_approval', 'Can do first level approval'), ('can_do_second_approval', 'Can do second level approval'), ('can_do_final_approval', 'Can do final approval'), ('can_reject_purchase', 'Can reject purchase')]},
        ),
        migrations.RemoveField(
            model_name='purchaseapproval',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='purchaseapproval',
            name='role',
        ),
        migrations.AddField(
            model_name='purchaseapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasebook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchasebook',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasebook',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasebook',
            name='stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.stock'),
        ),
        migrations.AddIndex(
            model_name='purchaseapproval',
            index=models.Index(fields=['purchase', 'sequence', 'status'], name='document_pu_purchas_60776a_idx'),
        ),
    ]
