# Generated by Django 5.1.1 on 2026-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_purchasebook_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebook',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
