# Generated by Django 5.1.1 on 2026-05-02 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_salesorderitem_salesorder'),
        ('payments', '0001_initial'),
        ('product', '0002_stock_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='credit_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_sales_orders', to='payments.creditid'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='product.stock'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='document.salesorder'),
        ),
    ]
