# Generated by Django 5.1.1 on 2026-05-08 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_salesorder_credit_customer_salesorderitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasebook',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_purchase', 'Can create purchase'), ('can_view_all_purchases', 'Can view all purchases'), ('can_cancel_purchase', 'Can cancel purchase'), ('can_do_first_approval_purchase', 'Can do first level purchase approval'), ('can_do_second_approval_purchase', 'Can do second level purchase approval'), ('can_do_final_approval_purchase', 'Can do final purchase approval'), ('can_reject_purchase', 'Can reject purchase')]},
        ),
        migrations.AlterModelOptions(
            name='salesorderitem',
            options={'permissions': [('can_view_all_sales', 'Can view all sales'), ('can_cancel_sale', 'Can cancel sale'), ('can_approve_sale_step_one', 'Can approve sale step one'), ('can_approve_sale_step_two', 'Can approve sale step two'), ('can_reject_sale', 'Can reject sale')]},
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_approvals', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='document.salesorderitem')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('sales_order', 'sequence')},
            },
        ),
    ]
