# Generated by Django 5.1.1 on 2026-05-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_stock_brand_stock_is_caterpillar_stock_is_original"),
        ("document", "0007_alter_purchasebook_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasebook",
            name="parent_stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_purchases",
                to="product.stock",
            ),
        ),
    ]

