# Generated by Django 5.1.1 on 2026-08-07 09:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_salesorder_backdated_fields'),
        ('product', '0007_backfill_stock_multilocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReturnItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to=settings.AUTH_USER_MODEL)),
                ('sales_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='document.salesorderitem')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to='product.stock')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_create_sale_return', 'Can create sale returns'), ('can_view_all_sale_returns', 'Can view all sale returns')],
            },
        ),
    ]
