# Generated by Django 5.1.1 on 2026-08-07 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_salesreturnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesreturnitem',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_sale_return', 'Can create sale returns'), ('can_approve_sale_return_step_one', 'Can approve sale return step one'), ('can_approve_sale_return_step_two', 'Can approve sale return step two'), ('can_reject_sale_return', 'Can reject sale return'), ('can_view_all_sale_returns', 'Can view all sale returns')]},
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SalesReturnApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_return_approvals', to=settings.AUTH_USER_MODEL)),
                ('sales_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='document.salesreturnitem')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['sales_return', 'sequence', 'status'], name='document_sa_sales_r_66362d_idx')],
                'unique_together': {('sales_return', 'sequence')},
            },
        ),
    ]
