# Generated by Django 5.1.1 on 2026-08-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_alter_salesreturnitem_options_salesreturnitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturnitem',
            name='returned_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
