# Generated by Django 5.1.1 on 2026-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_stock_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='brand',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_caterpillar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
