# Generated by Django 5.1.1 on 2026-06-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_stock_brand_stock_is_caterpillar_stock_is_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='part_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
