# Generated by Django 5.1.1 on 2026-06-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_stock_part_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('part_number', 'is_caterpillar', 'is_original', 'brand')},
        ),
    ]
