# Generated by Django 5.1.1 on 2026-07-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='stock_locations', to='product.location'),
        ),
        migrations.AddField(
            model_name='stock',
            name='top_level_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_level_stocks', to='product.location'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.location'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('part_number', 'is_caterpillar', 'is_original', 'brand', 'top_level_location')},
        ),
    ]
