# Generated by Django 5.1.1 on 2026-04-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['approval_priority', 'name'], 'permissions': [('manage_roles', 'Can manage roles')]},
        ),
    ]
