# Generated by Django 5.2.12 on 2026-03-11 08:29

from django.db import migrations


# def create_groups(apps, schema_editor):
#     Group = apps.get_model("auth", "Group")
# 
#     groups = [
#         "Location Manager",
#         "Floor Manager",
#         "Inventory Manager",
#     ]
# 
#     for name in groups:
#         Group.objects.get_or_create(name=name)
# 
# 
# def remove_groups(apps, schema_editor):
#     Group = apps.get_model("auth", "Group")
# 
#     groups = [
#         "Location Manager",
#         'Manger Level1'
#     ]
# 
#     Group.objects.filter(name__in=groups).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ("auth", "__latest__"),
    ]

    operations = [
        # migrations.RunPython(create_groups, remove_groups),
    ]
