# Generated by Django 5.2.12 on 2026-03-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_create_groups'),
    ]

    operations = [
    ]
