# Generated by Django 5.1.1 on 2026-06-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_signupinvite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='signupinvite',
            new_name='members_sig_email_ad02dd_idx',
            old_name='members_sig_email_2e9bf0_idx',
        ),
    ]
